import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import classes from "@/styles/Home.module.css";
import Hero from "@/components/home/Hero";
import About from "@/components/home/About";
import CallToAction from "@/components/home/CallToAction";
import ProductsSlideShow from "@/components/images/ProductsSlideShow";
import { fetch_cart_data } from "@/lib/fetch-data";
import ProductShowcase from "@/components/products/ProductShowcase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cozy Ember</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className={classes.products_display}>
        <ProductsSlideShow />
      </div>
      <ProductShowcase />
      <About />
      <CallToAction />
    </>
  );
}

export async function getServerSideProps() {
  const cartData = await fetch_cart_data();

  return {
    props: {
      cart: cartData,
    },
  };
}
